# Services
services:
  # MySQL Service
  mysql:
    container_name: mysql-container
    image: mysql:9.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      ventamed-network:
        ipv4_address: 192.168.10.2
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  redis:
    container_name: redis-container
    image: redis:7.4-alpine
    volumes:
      - redisdata:/data
    networks:
      ventamed-network:
        ipv4_address: 192.168.10.3
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10

  # PhpMyAdmin Service
  phpmyadmin:
    container_name: phpmyadmin-container
    image: phpmyadmin:5.2.1-fpm-alpine
    ports:
      - 8080:80
    networks:
      ventamed-network:
        ipv4_address: 192.168.10.4
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  # PHP Service
  php:
    container_name: php-container
    build: ./.docker/php
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    networks:
      ventamed-network:
        ipv4_address: 192.168.10.5
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Nginx Service
  nginx:
    container_name: nginx-container
    image: nginx:1.27-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - phpmyadmindata:/var/www/phpmyadmin
    networks:
      ventamed-network:
        ipv4_address: 192.168.10.6
    depends_on:
      - php
      - phpmyadmin

# Volumes
volumes:
  mysqldata:
  phpmyadmindata:
  redisdata:

#Networks
networks:
  ventamed-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1